train:
  batch_size: 16
  val_batch_size: 4
  epochs: 20
  lr: 0.0001
  weight_decay: 0.0001
  model_path: "checkpoints/best_model.pth"

model:
  num_classes: 19

data:
  train_image_dir: "path/to/train/images"
  train_label_dir: "path/to/train/labels"
  val_image_dir: "path/to/val/images"
  val_label_dir: "path/to/val/labels"
